# https://yarnpkg.com/configuration/yarnrc

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - '!{docs,src/**,{CHANGELOG,LICENSE,README}.md,package.json}'
  - '**/*.snap'
  - '**/*.spec.mts'
  - '**/*.spec-d.mts'

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableInlineBuilds: true

enableTransparentWorkspaces: false

injectEnvironmentFiles:
  - .env.repo?

nmHoistingLimits: workspaces

nodeLinker: node-modules

patchFolder: ./patches

yarnPath: .yarn/releases/yarn-4.8.0.cjs
