name: Epic
description: Define an overarching project goal or initiative
title: 🏔️ <title>
type: epic
labels:
  - type:epic
body:
  - type: markdown
    attributes:
      value: '## Overview'
  - type: input
    id: purpose
    attributes:
      label: Purpose
      description: The purpose of this epic.
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: High-level description of this epic.
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: The goals of this epic.
      value: |
        -
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Business Case'
  - type: textarea
    id: value-proposition
    attributes:
      label: Value Proposition
      description: How this epic impacts an initiative the business is working on.
    validations:
      required: true
  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: Describe or list how success will be measured and any leading indicators.
      value: |
        -
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Acceptance Criteria'
  - type: textarea
    id: conditions-of-satisfaction
    attributes:
      label: Conditions of Satisfaction
      description: |
        Specific, measurable, and verifiable conditions that must be met for this epic to be considered "done" and accepted by stakeholders.
      value: |
        -
    validations:
      required: true
  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: |
        Requirements that must be met to consider this epic complete and ready for release.
      placeholder: |
        - All tests pass with 100% coverage
        - Documentation is updated
        - Stakeholder approval is obtained
      value: |
        -
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Resources'
  - type: textarea
    id: tools-and-technology
    attributes:
      label: Tools & Technology
      description: Tools or technology that may be helpful while completing this epic.
  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to materials that may be helpful while completing this epic.
